project_name: smock

before:
  hooks:
    - go mod download

builds:
  - main: ./cmd/smock/main.go
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - 386

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc

brews:
  -
